version: '3.8'

services:
  fastapi:
    build: .
    container_name: classroom_book_app
    depends_on:
      - postgres
    ports:
      - "8003:8003"
    networks:
      - test

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8003:8003"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
    networks:
      - test

  postgres:
    image: postgres:latest
    container_name: db-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: class_booking_system
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - test

volumes:
  db-data:
    driver: local

networks:
  test:
    driver: bridge
